# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0002_entry_entry_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_style', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entry.Writing_Style'),
        ),
    ]
