# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0003_auto_20180319_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_length',
        ),
    ]
