# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0005_auto_20180321_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='user_yob',
            field=models.DateField(null=True),
        ),
    ]
