# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0011_auto_20180322_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_release_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
