# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0012_auto_20180322_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewed',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='reviewed',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='Reviewed',
        ),
        migrations.DeleteModel(
            name='Reviewer',
        ),
    ]
